color_counts = df.groupby(['Fruit', 'Color']).size().unstack()
print(color_counts)
color_counts.plot(kind='bar', stacked=True)
plt.title('Fruit Color Distribution')
plt.xlabel('Fruit')
plt.ylabel('Count')
plt.legend(title='Color')
plt.xticks(rotation=45)
plt.show()
